agents:
  queue: 'opensource'

steps:

  - label: ':android: Build fixture APK r21'
    key: "fixture-r21"
    timeout_in_minutes: 30
    agents:
      queue: macos-15
    artifact_paths:
      - "build/fixture-r21.apk"
      - "build/fixture-r21-url.txt"
      - "build/bs-fixture-r21-url.txt"
      - "build/fixture-r21/*"
    commands:
      - ruby scripts/build-test-fixture.rb
    env:
      ANDROID_NDK_ROOT: "/Users/administrator/Library/Android/sdk/ndk/26.1.10909125"
      JAVA_VERSION: 17

  - wait:

  # Android 11+ devices have the GWP-ASAN tool enabled which randomly samples native memory
  # to detect misuse (such as use-after-free, buffer overflow). If a failure is detected then
  # the device will raise a SIGABRT mentioning GWP-ASAN - this can be investigated further
  # by inspecting the devices logs.
  - label: ':bitbar: Android 16 NDK r21 end-to-end tests - batch 1'
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21-url.txt"
          - "build/fixture-r21/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/full_tests"
          - "--exclude=features/full_tests/[^a-k].*.feature"
          - "--exclude=features/full_tests/anr.feature"
          - "--app=@build/fixture-r21-url.txt"
          - "--appium-version=1.22"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--farm=bb"
          - "--device=ANDROID_16"
      test-collector#v1.10.2:
        files: "reports/TEST-*.xml"
        format: "junit"
        branch: "^main|next$$"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager

  - wait:

  - label: ':bitbar: Android 16 NDK r21 end-to-end tests - batch 2'
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21-url.txt"
          - "build/fixture-r21/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/full_tests"
          - "--exclude=features/full_tests/[^l-z].*.feature"
          - "--exclude=features/full_tests/anr.feature"
          - "--app=@build/fixture-r21-url.txt"
          - "--appium-version=1.22"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--farm=bb"
          - "--device=ANDROID_16"
      test-collector#v1.10.2:
        files: "reports/TEST-*.xml"
        format: "junit"
        branch: "^main|next$$"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager

