agents:
  queue: 'opensource'

steps:

  - label: ':android: Build fixture APK r28'
    key: "fixture-r28"
    timeout_in_minutes: 30
    agents:
      queue: macos-15
    artifact_paths:
      - "build/fixture-r28.apk"
      - "build/fixture-r28-url.txt"
      - "build/bs-fixture-r28-url.txt"
      - "build/fixture-r28/*"
    commands:
      - "ruby scripts/build-test-fixture.rb r28"
    env:
      ANDROID_NDK_ROOT: "/Users/administrator/Library/Android/sdk/ndk/26.1.10909125"
      JAVA_VERSION: 17

  - label: ':bitbar: {{matrix}} NDK r28 smoke tests'
    matrix:
      - "ANDROID_16"
    depends_on: "fixture-r28"
    timeout_in_minutes: 30
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r28-url.txt"
          - "build/fixture-r28/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/maze_output.zip"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/smoke_tests"
          - "--app=@build/fixture-r28-url.txt"
          - "--appium-version=1.22"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--farm=bb"
          - "--device={{matrix}}"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r28"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager

