steps:

#  - label: 'Tags'
#    timeout_in_minutes: 5
#    plugins:
#      docker-compose#v4.7.0:
#        pull: maze-runner
#        run: maze-runner
#        command:
#          - "features/full_tests/breadcrumb.feature"
#          - "--tags=@This"

  - label: 'Not tags'
    timeout_in_minutes: 5
    plugins:
      docker-compose#v5.3.0:
        pull: maze-runner
        run: maze-runner
        commands:
          - "--tags='not @This'"
          - "features/full_tests/breadcrumb.feature"

