steps:

  - label: ':android: Build fixture APK r19'
    key: "fixture-r19"
    timeout_in_minutes: 30
    agents:
      queue: macos-14
    artifact_paths:
      - "build/fixture-r19.apk"
      - "build/fixture-r19-url.txt"
      - "build/fixture-r19/*"
    commands:
      - bundle install
      - make fixture-r19
      - bundle exec upload-app --farm=bb --app=./build/fixture-r19.apk --app-id-file=build/fixture-r19-url.txt

  - label: ':bitbar: Android 8 NDK r19 smoke tests'
    depends_on: "fixture-r19"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r19-url.txt"
          - "build/fixture-r19/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/full_tests/anr.feature"
          - "--app=@build/fixture-r19-url.txt"
          - "--app-activity=com.bugsnag.android.mazerunner.MainActivity"
          - "--app-package=com.bugsnag.android.mazerunner"
          - "--appium-version=1.22"
          - "--farm=bb"
          - "--device=ANDROID_8"
          - "--no-tunnel"
          - "--aws-public-ip"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r19"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager

