steps:
  - label: ':docker: Build Android base image'
    plugins:
      - docker-compose#v2.6.0:
          build:
            - android-base
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
      - docker-compose#v2.6.0:
          push:
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest

  - wait

  - label: ':docker: Build Android linter image'
    plugins:
      - docker-compose#v2.6.0:
          build:
            - android-linter
          cache-from:
            - android-linter:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-linter:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
      - docker-compose#v2.6.0:
          push:
            - android-linter:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-linter:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest

  - label: ':docker: Build Android instrumentation image'
    plugins:
      - docker-compose#v2.6.0:
          build: android-instrumentation-tests
          cache-from:
            - android-instrumentation-tests:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-instrumentation-tests:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
      - docker-compose#v2.6.0:
          push:
            - android-instrumentation-tests:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-instrumentation-tests:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest

  - label: ':docker: Build Android apk builder image'
    plugins:
      - docker-compose#v2.6.0:
          build: android-builder
          cache-from:
            - android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
      - docker-compose#v2.6.0:
          push:
            - android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
    env:
      MAVEN_VERSION: "3.6.1"

  - label: ':docker: Build Android maze runner image'
    plugins:
      - docker-compose#v2.6.0:
          build: android-maze-runner

  - wait

  - label: ':android: Linter'
    plugins:
      - docker-compose#v2.6.0:
          run: android-linter

  - label: ':android: Build fixture APK'
    artifact_paths: build/fixture.apk
    plugins:
      - docker-compose#v2.6.0:
          run: android-builder
    env:
      MAVEN_VERSION: "3.6.1"

  - wait

  - label: ':android: Android 9 end-to-end tests'
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v2.6.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_9"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 16b SDK Instrumentation tests'
    plugins:
      - docker-compose#v2.6.0:
          run: android-instrumentation-tests
    env:
      APP_LOCATION: "/app/bugsnag-android-core/build/outputs/apk/androidTest/debug/bugsnag-android-core-debug-androidTest.apk"
      INSTRUMENTATION_DEVICES: '["Google Nexus 5-4.4", "Google Pixel-7.1", "Google Pixel 3-9.0"]'
      NDK_VERSION: "r16b"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - block: "Trigger full test suite"

  - label: ':android: Android 5 end-to-end tests'
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v2.6.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_5"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 6 end-to-end tests'
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v2.6.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_6"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 7 end-to-end tests'
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v2.6.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_7"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 8 end-to-end tests'
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v2.6.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_8"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 12b SDK Instrumentation tests'
    plugins:
      - docker-compose#v2.6.0:
          run: android-instrumentation-tests
    env:
      APP_LOCATION: "/app/bugsnag-android-core/build/outputs/apk/androidTest/debug/bugsnag-android-core-debug-androidTest.apk"
      INSTRUMENTATION_DEVICES: '["Google Nexus 5-4.4", "Google Pixel-7.1", "Google Pixel 3-9.0"]'
      NDK_VERSION: "r12b"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 19 SDK Instrumentation tests'
    plugins:
      - docker-compose#v2.6.0:
          run: android-instrumentation-tests
    env:
      APP_LOCATION: "/app/bugsnag-android-core/build/outputs/apk/androidTest/debug/bugsnag-android-core-debug-androidTest.apk"
      INSTRUMENTATION_DEVICES: '["Google Nexus 5-4.4", "Google Pixel-7.1", "Google Pixel 3-9.0"]'
      NDK_VERSION: "r19"
    concurrency: 5
    concurrency_group: 'browserstack-app'
