agents:
  queue: 'opensource'

steps:

  - label: ':android: Build fixture APK r19'
    key: "fixture-r19"
    timeout_in_minutes: 30
    agents:
      queue: macos-15
    artifact_paths:
      - "build/fixture-r19.apk"
      - "build/fixture-r19-url.txt"
      - "build/bs-fixture-r19-url.txt"
      - "build/fixture-r19/*"
    commands:
      - bundle install
      - make fixture-r19
      - bundle exec upload-app --farm=bb --app=./build/fixture-r19.apk --app-id-file=build/fixture-r19-url.txt
      - bundle exec upload-app --farm=bs --app=./build/fixture-r19.apk --app-id-file=build/bs-fixture-r19-url.txt
    env:
      JAVA_VERSION: 17

  #
  # BitBar steps
  #
  - label: ':bitbar: Android 7 NDK r19 smoke tests'
    depends_on: "fixture-r19"
    timeout_in_minutes: 30
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r19-url.txt"
          - "build/fixture-r19/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/smoke_tests/01_anr.feature"
          - "--app=@build/fixture-r19-url.txt"
          - "--appium-version=1.22"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--farm=bb"
          - "--device=ANDROID_7"
      test-collector#v1.10.2:
        files: "reports/TEST-*.xml"
        format: "junit"
        branch: "^main|next$$"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r19"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager

  - label: ':bitbar: Android 7 NDK r19 smoke tests'
    depends_on: "fixture-r19"
    timeout_in_minutes: 30
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r19-url.txt"
          - "build/fixture-r19/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/smoke_tests/01_anr.feature"
          - "--app=@build/fixture-r19-url.txt"
          - "--appium-version=1.22"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--farm=bb"
          - "--device=ANDROID_7"
      test-collector#v1.10.2:
        files: "reports/TEST-*.xml"
        format: "junit"
        branch: "^main|next$$"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r19"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager

  - label: ':bitbar: Android 7 NDK r19 smoke tests'
    depends_on: "fixture-r19"
    timeout_in_minutes: 30
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r19-url.txt"
          - "build/fixture-r19/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/smoke_tests/01_anr.feature"
          - "--app=@build/fixture-r19-url.txt"
          - "--appium-version=1.22"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--farm=bb"
          - "--device=ANDROID_7"
      test-collector#v1.10.2:
        files: "reports/TEST-*.xml"
        format: "junit"
        branch: "^main|next$$"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r19"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager

  - label: ':bitbar: Android 7 NDK r19 smoke tests'
    depends_on: "fixture-r19"
    timeout_in_minutes: 30
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r19-url.txt"
          - "build/fixture-r19/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/smoke_tests/01_anr.feature"
          - "--app=@build/fixture-r19-url.txt"
          - "--appium-version=1.22"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--farm=bb"
          - "--device=ANDROID_7"
      test-collector#v1.10.2:
        files: "reports/TEST-*.xml"
        format: "junit"
        branch: "^main|next$$"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r19"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager

