steps:
  - label: ':android: Build fixture APK r19'
    key: "fixture-r19"
    depends_on: "android-ci"
    timeout_in_minutes: 30
    artifact_paths: build/release/fixture-r19.apk
    plugins:
      - docker-compose#v3.7.0:
          run: android-builder
    env:
      MAVEN_VERSION: "3.6.1"
      TEST_FIXTURE_NDK_VERSION: "19.2.5345600"
      TEST_FIXTURE_NAME: "fixture-r19.apk"

  - label: ':android: Android 5 NDK r16 smoke tests'
    key: 'android-5-smoke'
    depends_on: "fixture-r16"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture-r16.apk"
          - "--farm=bs"
          - "--device=ANDROID_5_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 6 NDK r16 smoke tests'
    key: 'android-6-smoke'
    depends_on: "fixture-r16"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
        - "features/smoke_tests"
        - "--app=/app/build/release/fixture-r16.apk"
        - "--farm=bs"
        - "--device=ANDROID_6_0"
        - "--username=$BROWSER_STACK_USERNAME"
        - "--access-key=$BROWSER_STACK_ACCESS_KEY"
        - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 7 NDK r19 smoke tests'
    key: 'android-7-smoke'
    depends_on: "fixture-r19"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_7_1"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 8.0 NDK r19 smoke tests'
    key: 'android-8-smoke'
    depends_on: "fixture-r19"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_8_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 8.1 NDK r19 smoke tests'
    key: 'android-8-1-smoke'
    depends_on: "fixture-r19"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_8_1"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 9 NDK r21 smoke tests'
    key: 'android-9-smoke'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 10 NDK r21 smoke tests'
    key: 'android-10-smoke'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_10_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'