steps:
  - label: ':android: Build minimal fixture APK'
    key: "fixture-minimal"
    depends_on: "android-ci"
    timeout_in_minutes: 30
    artifact_paths: build/release/fixture-minimal.apk
    plugins:
      - docker-compose#v3.7.0:
          run: android-builder
    env:
      MAVEN_VERSION: "3.6.1"
      MINIMAL_FIXTURE: true
      TEST_FIXTURE_NDK_VERSION: "16.1.4479499"
      TEST_FIXTURE_NAME: "fixture-minimal.apk"

  - label: ':android: Build Example App'
    depends_on: "android-ci"
    timeout_in_minutes: 5
    command: 'cd examples/sdk-app-example && ./gradlew assembleRelease'
    plugins:
      docker-compose#v3.7.0:
        run: android-ci

  - label: ':android: Build Scan'
    depends_on: "android-ci"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    command: './gradlew clean assembleRelease check --scan'

  - label: ':android: Minimal fixture end-to-end tests'
    depends_on: "fixture-minimal"
    timeout_in_minutes: 30
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-minimal.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/minimal"
          - "--app=/app/build/release/fixture-minimal.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "--fail-fast"
          - "--tags"
          - "not @Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android size reporting'
    depends_on: "android-ci"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.7.0:
          run: android-sizer

  - label: ':android: Android 7 Instrumentation tests'
    depends_on:
      - "android-ci"
    timeout_in_minutes: 30
    command: ./scripts/build-instrumentation-tests.sh && ./scripts/run-instrumentation-test.sh
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    env:
      INSTRUMENTATION_DEVICES: '["Google Pixel-7.1"]'
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 9 Instrumentation tests'
    depends_on:
      - "android-ci"
    timeout_in_minutes: 30
    command: ./scripts/build-instrumentation-tests.sh && ./scripts/run-instrumentation-test.sh
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    env:
      INSTRUMENTATION_DEVICES: '["Google Pixel 3-9.0"]'
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 5 NDK r16 end-to-end tests - batch 1'
    depends_on:
      - "fixture-r16"
      - "android-5-smoke"
    timeout_in_minutes: 90
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_1"
          - "--app=/app/build/release/fixture-r16.apk"
          - "--farm=bs"
          - "--device=ANDROID_5_0"
          - "--fail-fast"
          - "--tags"
          - "not @Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 5 NDK r16 end-to-end tests - batch 2'
    depends_on:
      - "fixture-r16"
      - "android-5-smoke"
    timeout_in_minutes: 90
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_2"
          - "--app=/app/build/release/fixture-r16.apk"
          - "--farm=bs"
          - "--device=ANDROID_5_0"
          - "--fail-fast"
          - "--tags"
          - "not @Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 6 NDK r16 end-to-end tests - batch 1'
    depends_on:
      - "fixture-r16"
      - "android-6-smoke"
    timeout_in_minutes: 90
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_1"
          - "--app=/app/build/release/fixture-r16.apk"
          - "--farm=bs"
          - "--device=ANDROID_6_0"
          - "--fail-fast"
          - "--tags"
          - "not @Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 6 NDK r16 end-to-end tests - batch 2'
    depends_on:
      - "fixture-r16"
      - "android-6-smoke"
    timeout_in_minutes: 90
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_2"
          - "--app=/app/build/release/fixture-r16.apk"
          - "--farm=bs"
          - "--device=ANDROID_6_0"
          - "--fail-fast"
          - "--tags"
          - "not @Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 7 NDK r19 end-to-end tests - batch 1'
    depends_on:
      - "fixture-r19"
      - "android-7-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_1"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_7_1"
          - "--fail-fast"
          - "--tags"
          - "not @Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 7 NDK r19 end-to-end tests - batch 2'
    depends_on:
      - "fixture-r19"
      - "android-7-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_2"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_7_1"
          - "--fail-fast"
          - "--tags"
          - "not @Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 8.1 NDK r19 end-to-end tests - batch 1'
    depends_on:
      - "fixture-r19"
      - "android-8-1-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_1"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_8_1"
          - "--fail-fast"
          - "--tags"
          - "not @Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 8.1 NDK r19 end-to-end tests - batch 2'
    depends_on:
      - "fixture-r19"
      - "android-8-1-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_2"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_8_1"
          - "--fail-fast"
          - "--tags"
          - "not @Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 10 NDK r21 end-to-end tests - batch 1'
    depends_on:
      - "fixture-r21"
      - "android-10-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_1"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_10_0"
          - "--fail-fast"
          - "--tags"
          - "not @Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 10 NDK r21 end-to-end tests - batch 2'
    depends_on:
      - "fixture-r21"
      - "android-10-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_2"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_10_0"
          - "--fail-fast"
          - "--tags"
          - "not @Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  # Android 11+ devices have the GWP-ASAN tool enabled which randomly samples native memory to
  # to detect misuse (such as use-after-free, buffer overflow). If a failure is detected then
  # the device will raise a SIGABRT mentioning GWP-ASAN - this can be investigated further
  # by inspecting the devices logs.
  - label: ':android: Android 11 NDK r21 end-to-end tests - batch 1'
    depends_on:
      - "fixture-r21"
      - "android-11-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_1"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_11_0"
          - "--fail-fast"
          - "--tags"
          - "not @Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 11 NDK r21 end-to-end tests - batch 2'
    depends_on:
      - "fixture-r21"
      - "android-11-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_2"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_11_0"
          - "--fail-fast"
          - "--tags"
          - "not @Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  #
  # Flaky scenarios.  These should be skipped if there are no scenarios annotated with the @Flaky tag (as we should
  # always be aiming for) to avoid unnecessary CI wait times and potential flakes from resource unavailability.
  #
  - label: ':hankey: Flaky Android 4.4 NDK r16 end-to-end tests'
    skip: There are no @Flaky scenarios at present
    depends_on:
      - "fixture-r16"
    timeout_in_minutes: 90
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--retry=2"
          - "--strict-undefined"
          - "--strict-pending"
          - "--app=/app/build/release/fixture-r16.apk"
          - "--farm=bs"
          - "--device=ANDROID_4_4"
          - "--tags=@Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':hankey: Flaky Android 5 NDK r16 end-to-end tests'
    skip: There are no @Flaky scenarios at present
    depends_on:
      - "fixture-r16"
    timeout_in_minutes: 90
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--retry=2"
          - "--strict-undefined"
          - "--strict-pending"
          - "--app=/app/build/release/fixture-r16.apk"
          - "--farm=bs"
          - "--device=ANDROID_5_0"
          - "--tags=@Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':hankey: Flaky Android 6 NDK r16 end-to-end tests'
    skip: There are no @Flaky scenarios at present
    depends_on:
      - "fixture-r16"
    timeout_in_minutes: 90
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--retry=2"
          - "--strict-undefined"
          - "--strict-pending"
          - "--app=/app/build/release/fixture-r16.apk"
          - "--farm=bs"
          - "--device=ANDROID_6_0"
          - "--tags=@Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':hankey: Flaky Android 7 NDK r19 end-to-end tests'
    skip: There are no @Flaky scenarios at present
    depends_on:
      - "fixture-r19"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--retry=2"
          - "--strict-undefined"
          - "--strict-pending"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_7_1"
          - "--tags=@Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':hankey: Flaky Android 8.1 NDK r19 end-to-end tests'
    skip: There are no @Flaky scenarios at present
    depends_on:
      - "fixture-r19"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--retry=2"
          - "--strict-undefined"
          - "--strict-pending"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_8_1"
          - "--tags=@Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':hankey: Flaky Android 10 NDK r21 end-to-end tests'
    skip: There are no @Flaky scenarios at present
    depends_on:
      - "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--retry=2"
          - "--strict-undefined"
          - "--strict-pending"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_10_0"
          - "--tags=@Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':hankey: Flaky Android 11 NDK r21 end-to-end tests'
    skip: There are no @Flaky scenarios at present
    depends_on:
      - "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--retry=2"
          - "--strict-undefined"
          - "--strict-pending"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_11_0"
          - "--tags=@Flaky"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  # If there is a tag present activate a manual publishing step

  - block: 'Trigger package publish'
    key: trigger_publish
    if: build.branch == "master"
    blocked_state: passed

  - label: 'Publish :rocket:'
    if: build.branch == "master"
    depends_on:
      - 'trigger_publish'
    env:
      BUILDKITE_PLUGIN_S3_SECRETS_BUCKET_PREFIX: bugsnag-android-publish
    plugins:
      docker-compose#v3.7.0:
        no-cache: true
        run: android-publisher
