steps:
  - label: ':docker: Build Android base image'
    timeout_in_minutes: 30
    key: android-base
    plugins:
      - docker-compose#v2.6.0:
          build:
            - android-base
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
      - docker-compose#v2.6.0:
          push:
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest

  - label: ':docker: Build Android jvm test image'
    key: android-jvm
    depends_on: android-base
    timeout_in_minutes: 40
    plugins:
      - docker-compose#v2.6.0:
          build:
            - android-jvm
          cache-from:
            - android-jvm:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-jvm:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
      - docker-compose#v2.6.0:
          push:
            - android-jvm:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-jvm:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest

  - label: ':docker: Build Android apk builder image'
    key: android-builder
    depends_on: android-base
    timeout_in_minutes: 40
    plugins:
      - docker-compose#v2.6.0:
          build: android-builder
          cache-from:
            - android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
      - docker-compose#v2.6.0:
          push:
            - android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
    env:
      MAVEN_VERSION: "3.6.1"

  - label: ':android: Build fixture APK'
    key: build-apk
    depends_on: android-builder
    timeout_in_minutes: 30
    artifact_paths: build/fixture.apk
    plugins:
      - docker-compose#v2.6.0:
          run: android-builder
    env:
      MAVEN_VERSION: "3.6.1"

  - label: ':docker: Build Android sizer image'
    timeout_in_minutes: 40
    depends_on: android-base
    plugins:
      - docker-compose#v2.6.0:
          build: android-sizer
          cache-from:
            - android-sizer:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-sizer-${BRANCH_NAME}
            - android-sizer:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-sizer-latest
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
      - docker-compose#v2.6.0:
          push:
            - android-sizer:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-sizer-${BRANCH_NAME}
            - android-sizer:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-sizer-latest
    env:
      MAVEN_VERSION: "3.6.1"

  - label: ':android: Android size reporting'
    depends_on: android-base
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v2.6.0:
          run: android-sizer

  - label: ':android: Linter'
    depends_on: android-jvm
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v2.6.0:
          run: android-jvm
    command: 'bash ./scripts/run-linter.sh'

  - label: ':android: JVM tests'
    depends_on: android-jvm
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v2.6.0:
          run: android-jvm
    command: './gradlew test'

  - label: ':android: Android 6 end-to-end tests - batch 1'
    depends_on:
      - build-apk
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.4.0:
        download: "build/fixture.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "--exclude=features/[^a-h].*.feature"
          - "--app=/app/build/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_6"
          #- "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 6 end-to-end tests - batch 2'
    depends_on:
      - build-apk
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.4.0:
        download: "build/fixture.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "--exclude=features/[^i-z].*.feature"
          - "--app=/app/build/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_6"
          #- "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 7 end-to-end tests - batch 1'
    depends_on:
      - build-apk
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.4.0:
        download: "build/fixture.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "--exclude=features/[^a-h].*.feature"
          - "--app=/app/build/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_7"
          #- "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 7 end-to-end tests - batch 2'
    depends_on:
      - build-apk
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.4.0:
        download: "build/fixture.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "--exclude=features/[^i-z].*.feature"
          - "--app=/app/build/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_7"
          #- "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 8 end-to-end tests - batch 1'
    depends_on:
      - build-apk
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.4.0:
        download: "build/fixture.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "--exclude=features/[^a-h].*.feature"
          - "--app=/app/build/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_8"
          #- "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 8 end-to-end tests - batch 2'
    depends_on:
      - build-apk
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.4.0:
        download: "build/fixture.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "--exclude=features/[^i-z].*.feature"
          - "--app=/app/build/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_8"
          #- "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 9 end-to-end tests - batch 1'
    depends_on:
      - build-apk
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.4.0:
        download: "build/fixture.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "--exclude=features/[^a-h].*.feature"
          - "--app=/app/build/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_6"
          #- "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 9 end-to-end tests - batch 2'
    depends_on:
      - build-apk
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.4.0:
        download: "build/fixture.apk"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "--exclude=features/[^i-z].*.feature"
          - "--app=/app/build/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_6"
          #- "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
