steps:
  - label: ':android: Android 5 NDK r16 smoke tests'
    key: 'android-5-smoke'
    depends_on: "fixture-r16"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture-r16.apk"
          - "--farm=bs"
          - "--device=ANDROID_5_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 6 NDK r16 smoke tests'
    key: 'android-6-smoke'
    depends_on: "fixture-r16"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
        - "features/smoke_tests"
        - "--app=/app/build/release/fixture-r16.apk"
        - "--farm=bs"
        - "--device=ANDROID_6_0"
        - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android 7 NDK r19 smoke tests'
    key: 'android-7-smoke'
    depends_on: "fixture-r19"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_7_1"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android 8.1 NDK r19 smoke tests'
    key: 'android-8-1-smoke'
    depends_on: "fixture-r19"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_8_1"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android 9 NDK r21 smoke tests'
    key: 'android-9-smoke'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android 9 NDK r21 end-to-end tests - batch 1'
    depends_on:
      - "fixture-r21"
      - "android-9-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_1"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android 9 NDK r21 end-to-end tests - batch 2'
    depends_on:
      - "fixture-r21"
      - "android-9-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_2"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android 10 NDK r21 smoke tests'
    key: 'android-10-smoke'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_10_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
