steps:
  - label: ":toolbox:"
    plugins:
      - docker#v3.7.0:
          image: gusto/buildkite-builder:2.1.0
          propagate-environment: true
          command: "env"

#  - label: 'Trigger RN tests for all builds of our next branch'
#    if: build.branch == "next"
#    trigger: 'bugsnag-js'
#    build:
#      branch: 'next'
#      message: 'Run RN tests with latest Android next branch'
#      env:
#        BUILD_RN_WITH_LATEST_NATIVES: "true"
#    async: true

