steps:
  - label: ':android: Build minimal fixture APK'
    key: "fixture-minimal"
    depends_on: "android-ci"
    timeout_in_minutes: 30
    artifact_paths: build/release/fixture-minimal.apk
    plugins:
      - docker-compose#v3.7.0:
          run: android-builder
    env:
      MAVEN_VERSION: "3.6.1"
      MINIMAL_FIXTURE: true
      TEST_FIXTURE_NDK_VERSION: "16.1.4479499"
      TEST_FIXTURE_NAME: "fixture-minimal.apk"

  - label: ':android: Build Example App'
    depends_on: "android-ci"
    timeout_in_minutes: 5
    command: 'cd examples/sdk-app-example && ./gradlew assembleRelease'
    plugins:
      docker-compose#v3.7.0:
        run: android-ci

  - label: ':android: Build Scan'
    depends_on: "android-ci"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    command: './gradlew clean assembleRelease check --scan'

  - label: ':android: Minimal fixture end-to-end tests'
    depends_on: "fixture-minimal"
    timeout_in_minutes: 30
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-minimal.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "--app=/app/build/release/fixture-minimal.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
          - "features/full_tests/handled_exception.feature"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android size reporting'
    depends_on: "android-ci"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.7.0:
          run: android-sizer

  - label: ':android: Android 7 Instrumentation tests'
    depends_on:
      - "android-ci"
      - "NDK-smoke-test"
    timeout_in_minutes: 30
    command: ./scripts/build-instrumentation-tests.sh && ./scripts/run-instrumentation-test.sh
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    env:
      INSTRUMENTATION_DEVICES: '["Google Pixel-7.1"]'
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 9 Instrumentation tests'
    depends_on:
      - "android-ci"
      - "NDK-smoke-test"
    timeout_in_minutes: 30
    command: ./scripts/build-instrumentation-tests.sh && ./scripts/run-instrumentation-test.sh
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    env:
      INSTRUMENTATION_DEVICES: '["Google Pixel 3-9.0"]'
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 4.4 NDK r16 end-to-end tests'
    depends_on:
      - "fixture-r16"
      - "android-4-4-smoke"
    timeout_in_minutes: 90
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture-r16.apk"
          - "--farm=bs"
          - "--device=ANDROID_4_4"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 5 NDK r16 end-to-end tests'
    depends_on:
      - "fixture-r16"
      - "android-5-smoke"
    timeout_in_minutes: 90
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture-r16.apk"
          - "--farm=bs"
          - "--device=ANDROID_5_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 6 NDK r16 end-to-end tests'
    depends_on:
      - "fixture-r16"
      - "android-6-smoke"
    timeout_in_minutes: 90
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture-r16.apk"
          - "--farm=bs"
          - "--device=ANDROID_6_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 7 NDK r19 end-to-end tests'
    depends_on:
      - "fixture-r19"
      - "android-7-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_7_1"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 8.0 NDK r19 end-to-end tests'
    depends_on:
      - "fixture-r19"
      - "android-8-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_8_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 8.1 NDK r19 end-to-end tests'
    depends_on:
      - "fixture-r19"
      - "android-8-1-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_8_1"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 9 NDK r21 end-to-end tests'
    depends_on:
      - "fixture-r21"
      - "android-9-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 10 NDK r21 end-to-end tests'
    depends_on:
      - "fixture-r21"
      - "android-10-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_10_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 11 NDK r21 end-to-end tests'
    depends_on:
      - "fixture-r21"
      - "android-11-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_11_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
