steps:

  - label: 'Audit current licenses'
    timeout_in_minutes: 30
    agents:
      queue: ms-arm-12-7
    command: ./scripts/audit-dependency-licenses.sh

  - label: ':android: Build fixture APK r16'
    timeout_in_minutes: 30
    agents:
      queue: ms-arm-12-7
    artifact_paths:
      - "build/fixture-r16.apk"
      - "build/fixture_r16_url.txt"
      - "build/fixture-r16/*"
    commands:
      - bundle install
      - make fixture-r16
      - bundle exec upload-app --app=./build/fixture-r16.apk --app-id-file=build/fixture_r16_url.txt

  - label: ':android: Build fixture APK r16'
    timeout_in_minutes: 30
    agents:
      queue: ms-arm-12-7
    artifact_paths:
      - "build/fixture-r16.apk"
      - "build/fixture_r16_url.txt"
      - "build/fixture-r16/*"
    commands:
      - bundle install
      - make fixture-r16
      - bundle exec upload-app --app=./build/fixture-r16.apk --app-id-file=build/fixture_r16_url.txt

  - label: ':android: Build fixture APK r16'
    timeout_in_minutes: 30
    agents:
      queue: ms-arm-12-7
    artifact_paths:
      - "build/fixture-r16.apk"
      - "build/fixture_r16_url.txt"
      - "build/fixture-r16/*"
    commands:
      - bundle install
      - make fixture-r16
      - bundle exec upload-app --app=./build/fixture-r16.apk --app-id-file=build/fixture_r16_url.txt

  - label: ':android: Build fixture APK r16'
    timeout_in_minutes: 30
    agents:
      queue: ms-arm-12-7
    artifact_paths:
      - "build/fixture-r16.apk"
      - "build/fixture_r16_url.txt"
      - "build/fixture-r16/*"
    commands:
      - bundle install
      - make fixture-r16
      - bundle exec upload-app --app=./build/fixture-r16.apk --app-id-file=build/fixture_r16_url.txt

  - label: ':android: Build fixture APK r16'
    timeout_in_minutes: 30
    agents:
      queue: ms-arm-12-7
    artifact_paths:
      - "build/fixture-r16.apk"
      - "build/fixture_r16_url.txt"
      - "build/fixture-r16/*"
    commands:
      - bundle install
      - make fixture-r16
      - bundle exec upload-app --app=./build/fixture-r16.apk --app-id-file=build/fixture_r16_url.txt

  - label: ':android: Build fixture APK r16'
    timeout_in_minutes: 30
    agents:
      queue: ms-arm-12-7
    artifact_paths:
      - "build/fixture-r16.apk"
      - "build/fixture_r16_url.txt"
      - "build/fixture-r16/*"
    commands:
      - bundle install
      - make fixture-r16
      - bundle exec upload-app --app=./build/fixture-r16.apk --app-id-file=build/fixture_r16_url.txt

  - label: ':android: Build fixture APK r16'
    timeout_in_minutes: 30
    agents:
      queue: ms-arm-12-7
    artifact_paths:
      - "build/fixture-r16.apk"
      - "build/fixture_r16_url.txt"
      - "build/fixture-r16/*"
    commands:
      - bundle install
      - make fixture-r16
      - bundle exec upload-app --app=./build/fixture-r16.apk --app-id-file=build/fixture_r16_url.txt

  - label: ':android: Build fixture APK r16'
    timeout_in_minutes: 30
    agents:
      queue: ms-arm-12-7
    artifact_paths:
      - "build/fixture-r16.apk"
      - "build/fixture_r16_url.txt"
      - "build/fixture-r16/*"
    commands:
      - bundle install
      - make fixture-r16
      - bundle exec upload-app --app=./build/fixture-r16.apk --app-id-file=build/fixture_r16_url.txt

  - label: ':android: Build fixture APK r16'
    timeout_in_minutes: 30
    agents:
      queue: ms-arm-12-7
    artifact_paths:
      - "build/fixture-r16.apk"
      - "build/fixture_r16_url.txt"
      - "build/fixture-r16/*"
    commands:
      - bundle install
      - make fixture-r16
      - bundle exec upload-app --app=./build/fixture-r16.apk --app-id-file=build/fixture_r16_url.txt

  - label: ':android: Build fixture APK r16'
    timeout_in_minutes: 30
    agents:
      queue: ms-arm-12-7
    artifact_paths:
      - "build/fixture-r16.apk"
      - "build/fixture_r16_url.txt"
      - "build/fixture-r16/*"
    commands:
      - bundle install
      - make fixture-r16
      - bundle exec upload-app --app=./build/fixture-r16.apk --app-id-file=build/fixture_r16_url.txt

