steps:
  - label: ':android: Build minimal fixture APK'
    key: "fixture-minimal"
    depends_on: "android-ci"
    timeout_in_minutes: 30
    artifact_paths: build/release/fixture-minimal.apk
    plugins:
      - docker-compose#v3.7.0:
          run: android-builder
    env:
      MAVEN_VERSION: "3.6.1"
      MINIMAL_FIXTURE: true
      TEST_FIXTURE_NDK_VERSION: "17.2.4988734"
      TEST_FIXTURE_NAME: "fixture-minimal.apk"
      BUILD_TASK: "assembleRelease"

  - label: ':android: Build Example App'
    depends_on: "android-ci"
    timeout_in_minutes: 5
    command: 'cd examples/sdk-app-example && ./gradlew clean assembleRelease'
    plugins:
      docker-compose#v3.7.0:
        run: android-ci

  - label: ':android: Build debug fixture APK'
    key: "fixture-debug"
    depends_on: "android-ci"
    timeout_in_minutes: 30
    artifact_paths: build/debug/fixture-debug.apk
    plugins:
      - docker-compose#v3.7.0:
          run: android-builder
    env:
      MAVEN_VERSION: "3.6.1"
      MINIMAL_FIXTURE: false
      TEST_FIXTURE_NDK_VERSION: "17.2.4988734"
      TEST_FIXTURE_NAME: "fixture-debug.apk"
      BUILD_TASK: "assembleDebug"

  - label: ':android: Build Scan'
    depends_on: "android-ci"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    command: './gradlew clean assembleRelease check --scan'

  - label: ':android: Minimal fixture end-to-end tests'
    depends_on: "fixture-minimal"
    timeout_in_minutes: 30
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-minimal.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/minimal"
          - "--app=/app/build/release/fixture-minimal.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Debug fixture smoke tests'
    depends_on: "fixture-debug"
    timeout_in_minutes: 30
    plugins:
      artifacts#v1.2.0:
        download: "build/debug/fixture-debug.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--tags=debug-safe"
          - "--app=/app/build/debug/fixture-debug.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android size reporting'
    depends_on: "android-ci"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.7.0:
          run: android-sizer

  - label: ':android: Android 5 NDK r16 end-to-end tests - batch 1'
    depends_on:
      - "fixture-r16"
      - "android-5-smoke"
    timeout_in_minutes: 90
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_1"
          - "--app=/app/build/release/fixture-r16.apk"
          - "--farm=bs"
          - "--device=ANDROID_5_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 5 NDK r16 end-to-end tests - batch 2'
    depends_on:
      - "fixture-r16"
      - "android-5-smoke"
    timeout_in_minutes: 90
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_2"
          - "--app=/app/build/release/fixture-r16.apk"
          - "--farm=bs"
          - "--device=ANDROID_5_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 6 NDK r16 end-to-end tests - batch 1'
    depends_on:
      - "fixture-r16"
      - "android-6-smoke"
    timeout_in_minutes: 90
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_1"
          - "--app=/app/build/release/fixture-r16.apk"
          - "--farm=bs"
          - "--device=ANDROID_6_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android 6 NDK r16 end-to-end tests - batch 2'
    depends_on:
      - "fixture-r16"
      - "android-6-smoke"
    timeout_in_minutes: 90
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r16.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_2"
          - "--app=/app/build/release/fixture-r16.apk"
          - "--farm=bs"
          - "--device=ANDROID_6_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android 7 NDK r19 end-to-end tests - batch 1'
    depends_on:
      - "fixture-r19"
      - "android-7-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_1"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_7_1_SAMSUNG_GALAXY_NOTE_8"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android 7 NDK r19 end-to-end tests - batch 2'
    depends_on:
      - "fixture-r19"
      - "android-7-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_2"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_7_1_SAMSUNG_GALAXY_NOTE_8"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android 8.1 NDK r19 end-to-end tests - batch 1'
    depends_on:
      - "fixture-r19"
      - "android-8-1-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_1"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_8_1"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android 8.1 NDK r19 end-to-end tests - batch 2'
    depends_on:
      - "fixture-r19"
      - "android-8-1-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r19.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_2"
          - "--app=/app/build/release/fixture-r19.apk"
          - "--farm=bs"
          - "--device=ANDROID_8_1"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android 10 NDK r21 end-to-end tests - batch 1'
    depends_on:
      - "fixture-r21"
      - "android-10-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_1"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_10_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android 10 NDK r21 end-to-end tests - batch 2'
    depends_on:
      - "fixture-r21"
      - "android-10-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_2"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_10_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  # Android 11+ devices have the GWP-ASAN tool enabled which randomly samples native memory
  # to detect misuse (such as use-after-free, buffer overflow). If a failure is detected then
  # the device will raise a SIGABRT mentioning GWP-ASAN - this can be investigated further
  # by inspecting the devices logs.
  - label: ':android: Android 11 NDK r21 end-to-end tests - batch 1'
    depends_on:
      - "fixture-r21"
      - "android-11-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_1"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_11_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android 11 NDK r21 end-to-end tests - batch 2'
    depends_on:
      - "fixture-r21"
      - "android-11-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_2"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_11_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  # Android 11+ devices have the GWP-ASAN tool enabled which randomly samples native memory
  # to detect misuse (such as use-after-free, buffer overflow). If a failure is detected then
  # the device will raise a SIGABRT mentioning GWP-ASAN - this can be investigated further
  # by inspecting the devices logs.
  - label: ':android: Android 12 NDK r21 end-to-end tests - batch 1'
    depends_on:
      - "fixture-r21"
      - "android-12-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_1"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_12_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android 12 NDK r21 end-to-end tests - batch 2'
    depends_on:
      - "fixture-r21"
      - "android-12-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests/batch_2"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=bs"
          - "--device=ANDROID_12_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  # If there is a tag present activate a manual publishing step

  - block: 'Trigger package publish'
    key: trigger_publish
    if: build.branch == "master"
    blocked_state: passed

  - label: 'Publish :rocket:'
    if: build.branch == "master"
    depends_on:
      - 'trigger_publish'
    env:
      BUILDKITE_PLUGIN_S3_SECRETS_BUCKET_PREFIX: bugsnag-android-publish
    plugins:
      docker-compose#v3.7.0:
        no-cache: true
        run: android-publisher
