steps:
  - label: ':docker: Build Android base image'
    timeout_in_minutes: 30
    key: android-base
    plugins:
      - docker-compose#v2.6.0:
          build:
            - android-base
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
      - docker-compose#v2.6.0:
          push:
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest

  - label: ':docker: Build Android jvm test image'
    key: android-jvm
    depends_on: android-base
    timeout_in_minutes: 40
    plugins:
      - docker-compose#v2.6.0:
          build:
            - android-jvm
          cache-from:
            - android-jvm:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-jvm:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
      - docker-compose#v2.6.0:
          push:
            - android-jvm:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-jvm:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest

  - label: ':docker: Build Android instrumentation image'
    timeout_in_minutes: 40
    key: android-instrumentation-tests
    depends_on: android-base
    plugins:
      - docker-compose#v2.6.0:
          build: android-instrumentation-tests
          cache-from:
            - android-instrumentation-tests:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-instrumentation-tests:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
      - docker-compose#v2.6.0:
          push:
            - android-instrumentation-tests:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-instrumentation-tests:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest

  - label: ':docker: Build Android apk builder image'
    key: android-builder
    depends_on: android-base
    timeout_in_minutes: 40
    plugins:
      - docker-compose#v2.6.0:
          build: android-builder
          cache-from:
            - android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
      - docker-compose#v2.6.0:
          push:
            - android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
    env:
      MAVEN_VERSION: "3.6.1"

  - label: ':android: Build fixture APK'
    key: build-apk
    depends_on: android-base
    timeout_in_minutes: 30
    artifact_paths: build/fixture.apk
    plugins:
      - docker-compose#v2.6.0:
          run: android-builder
    env:
      MAVEN_VERSION: "3.6.1"

  - label: ':docker: Build Android sizer image'
    timeout_in_minutes: 40
    depends_on: android-base
    plugins:
      - docker-compose#v2.6.0:
          build: android-sizer
          cache-from:
            - android-sizer:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-sizer-${BRANCH_NAME}
            - android-sizer:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-sizer-latest
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
      - docker-compose#v2.6.0:
          push:
            - android-sizer:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-sizer-${BRANCH_NAME}
            - android-sizer:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-sizer-latest
    env:
      MAVEN_VERSION: "3.6.1"

  - label: ':android: Android size reporting'
    depends_on: android-base
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v2.6.0:
          run: android-sizer

  - label: ':android: Linter'
    depends_on: android-jvm
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v2.6.0:
          run: android-jvm
    command: 'bash ./scripts/run-linter.sh'

  - label: ':android: JVM tests'
    depends_on: android-jvm
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v2.6.0:
          run: android-jvm
    command: './gradlew test'

  - label: ':android: Android 9 end-to-end tests'
    depends_on:
      - build-apk
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v2.6.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_9"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 16b SDK 9.0 Instrumentation tests'
    depends_on: android-instrumentation-tests
    timeout_in_minutes: 60
    plugins:
      - docker-compose#v2.6.0:
          run: android-instrumentation-tests
    env:
      APP_LOCATION: "/app/bugsnag-android-core/build/outputs/apk/androidTest/debug/bugsnag-android-core-debug-androidTest.apk"
      INSTRUMENTATION_DEVICES: '["Google Pixel 3-9.0"]'
      NDK_VERSION: "r16b"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - block: "Trigger full test suite"
    key: block-step

  - label: ':android: Android 5 end-to-end tests'
    depends_on:
      - block-step
      - build-apk
    skip: Temporarily disabled due to flakiness with BrowserStack tunneling
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v2.6.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_5"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 6 end-to-end tests'
    depends_on:
      - block-step
      - build-apk
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v2.6.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_6"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 7 end-to-end tests'
    depends_on:
      - block-step
      - build-apk
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v2.6.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_7"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 8 end-to-end tests'
    depends_on:
      - block-step
      - build-apk
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v2.6.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_8"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 16b SDK 4.4 Instrumentation tests'
    depends_on:
      - block-step
      - android-instrumentation-tests
    timeout_in_minutes: 60
    plugins:
      - docker-compose#v2.6.0:
          run: android-instrumentation-tests
    env:
      APP_LOCATION: "/app/bugsnag-android-core/build/outputs/apk/androidTest/debug/bugsnag-android-core-debug-androidTest.apk"
      INSTRUMENTATION_DEVICES: '["Google Nexus 5-4.4"]'
      NDK_VERSION: "r16b"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 16b SDK 7.1 Instrumentation tests'
    depends_on:
      - block-step
      - android-instrumentation-tests
    timeout_in_minutes: 60
    plugins:
      - docker-compose#v2.6.0:
          run: android-instrumentation-tests
    env:
      APP_LOCATION: "/app/bugsnag-android-core/build/outputs/apk/androidTest/debug/bugsnag-android-core-debug-androidTest.apk"
      INSTRUMENTATION_DEVICES: '["Google Pixel-7.1"]'
      NDK_VERSION: "r16b"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 12b SDK 4.4 Instrumentation tests'
    depends_on:
      - block-step
      - android-instrumentation-tests
    timeout_in_minutes: 60
    plugins:
      - docker-compose#v2.6.0:
          run: android-instrumentation-tests
    env:
      APP_LOCATION: "/app/bugsnag-android-core/build/outputs/apk/androidTest/debug/bugsnag-android-core-debug-androidTest.apk"
      INSTRUMENTATION_DEVICES: '["Google Nexus 5-4.4"]'
      NDK_VERSION: "r12b"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 12b SDK 7.1 Instrumentation tests'
    depends_on:
      - block-step
      - android-instrumentation-tests
    timeout_in_minutes: 60
    plugins:
      - docker-compose#v2.6.0:
          run: android-instrumentation-tests
    env:
      APP_LOCATION: "/app/bugsnag-android-core/build/outputs/apk/androidTest/debug/bugsnag-android-core-debug-androidTest.apk"
      INSTRUMENTATION_DEVICES: '["Google Pixel-7.1"]'
      NDK_VERSION: "r12b"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 12b SDK 9.0 Instrumentation tests'
    depends_on:
      - block-step
      - android-instrumentation-tests
    timeout_in_minutes: 60
    plugins:
      - docker-compose#v2.6.0:
          run: android-instrumentation-tests
    env:
      APP_LOCATION: "/app/bugsnag-android-core/build/outputs/apk/androidTest/debug/bugsnag-android-core-debug-androidTest.apk"
      INSTRUMENTATION_DEVICES: '["Google Pixel 3-9.0"]'
      NDK_VERSION: "r12b"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 19 SDK 4.4 Instrumentation tests'
    depends_on:
      - block-step
      - android-instrumentation-tests
    timeout_in_minutes: 60
    plugins:
      - docker-compose#v2.6.0:
          run: android-instrumentation-tests
    env:
      APP_LOCATION: "/app/bugsnag-android-core/build/outputs/apk/androidTest/debug/bugsnag-android-core-debug-androidTest.apk"
      INSTRUMENTATION_DEVICES: '["Google Nexus 5-4.4"]'
      NDK_VERSION: "r19"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 19 SDK 7.1 Instrumentation tests'
    depends_on:
      - block-step
      - android-instrumentation-tests
    timeout_in_minutes: 60
    plugins:
      - docker-compose#v2.6.0:
          run: android-instrumentation-tests
    env:
      APP_LOCATION: "/app/bugsnag-android-core/build/outputs/apk/androidTest/debug/bugsnag-android-core-debug-androidTest.apk"
      INSTRUMENTATION_DEVICES: '["Google Pixel-7.1"]'
      NDK_VERSION: "r19"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 19 SDK 9.0 Instrumentation tests'
    depends_on:
      - block-step
      - android-instrumentation-tests
    timeout_in_minutes: 60
    plugins:
      - docker-compose#v2.6.0:
          run: android-instrumentation-tests
    env:
      APP_LOCATION: "/app/bugsnag-android-core/build/outputs/apk/androidTest/debug/bugsnag-android-core-debug-androidTest.apk"
      INSTRUMENTATION_DEVICES: '["Google Pixel 3-9.0"]'
      NDK_VERSION: "r19"
    concurrency: 5
    concurrency_group: 'browserstack-app'
