steps:

  - label: ':android: Build fixture APK r21'
    key: "fixture-r21"
    timeout_in_minutes: 30
    agents:
      queue: macos-14
    artifact_paths:
      - "build/fixture-r21.apk"
      - "build/fixture-r21-url.txt"
      - "build/fixture-r21/*"
    commands:
      - bundle install
      - make fixture-r21
      - bundle exec upload-app --farm=bb --app=./build/fixture-r21.apk --app-id-file=build/fixture-r21-url.txt
    env:
      JAVA_VERSION: 17

  - label: ':bitbar: Android 9 NDK r21 smoke tests'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21-url.txt"
          - "build/fixture-r21/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/anr.feature"
          - "--app=@build/fixture-r21-url.txt"
          - "--app-activity=com.bugsnag.android.mazerunner.MainActivity"
          - "--app-package=com.bugsnag.android.mazerunner"
          - "--appium-version=1.22"
          - "--farm=bb"
          - "--device=ANDROID_9"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager

