steps:
  - label: ':android: Build minimal fixture APK'
    key: "fixture-minimal"
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    artifact_paths: build/fixture-minimal.apk
    command: make fixture-minimal

  - label: ':android: Build Example App'
    timeout_in_minutes: 5
    agents:
      queue: macos-12-arm
    command: 'make example-app'

  - label: ':android: Build debug fixture APK'
    key: "fixture-debug"
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    artifact_paths:
      - "build/fixture-debug.apk"
      - "build/fixture-debug/*"
    command: make fixture-debug

  - label: ':android: Build Scan'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    command: './gradlew clean assembleRelease check --scan'

  #
  # BitBar steps
  #

  - label: ':bitbar: Minimal fixture end-to-end tests'
    depends_on: "fixture-minimal"
    timeout_in_minutes: 30
    plugins:
      artifacts#v1.9.0:
        download: "build/fixture-minimal.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/minimal"
          - "--app=/app/build/fixture-minimal.apk"
          - "--farm=bb"
          - "--device=ANDROID_9"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: Debug fixture smoke tests'
    depends_on: "fixture-debug"
    timeout_in_minutes: 30
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-debug.apk"
          - "build/fixture-debug/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/smoke_tests"
          - "--tags=debug-safe"
          - "--app=/app/build/fixture-debug.apk"
          - "--farm=bb"
          - "--device=ANDROID_9"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-debug"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: Android 7 NDK r19 end-to-end tests - batch 1'
    depends_on: "fixture-r19"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r19.apk"
          - "build/fixture-r19/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/full_tests"
          - "--app=build/fixture-r19.apk"
          - "--farm=bb"
          - "--device=ANDROID_7"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--exclude=features/full_tests/[^a-k].*.feature"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r19"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: Android 7 NDK r19 end-to-end tests - batch 2'
    depends_on: "fixture-r19"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r19.apk"
          - "build/fixture-r19/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/full_tests"
          - "--exclude=features/full_tests/[^l-z].*.feature"
          - "--app=build/fixture-r19.apk"
          - "--farm=bb"
          - "--device=ANDROID_7"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r19"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: Android 8 NDK r19 end-to-end tests - batch 1'
    depends_on: "fixture-r19"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r19.apk"
          - "build/fixture-r19/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/full_tests"
          - "--app=build/fixture-r19.apk"
          - "--farm=bb"
          - "--device=ANDROID_8"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--exclude=features/full_tests/[^a-k].*.feature"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r19"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: Android 8 NDK r19 end-to-end tests - batch 2'
    depends_on: "fixture-r19"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r19.apk"
          - "build/fixture-r19/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/full_tests"
          - "--exclude=features/full_tests/[^l-z].*.feature"
          - "--app=build/fixture-r19.apk"
          - "--farm=bb"
          - "--device=ANDROID_8"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r19"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: Android 9 NDK r21 end-to-end tests - batch 1'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21.apk"
          - "build/fixture-r21/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/full_tests"
          - "--app=build/fixture-r21.apk"
          - "--farm=bb"
          - "--device=ANDROID_9"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--exclude=features/full_tests/[^a-k].*.feature"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: Android 9 NDK r21 end-to-end tests - batch 2'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21.apk"
          - "build/fixture-r21/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/full_tests"
          - "--exclude=features/full_tests/[^l-z].*.feature"
          - "--app=build/fixture-r21.apk"
          - "--farm=bb"
          - "--device=ANDROID_9"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: Android 10 NDK r21 end-to-end tests - batch 1'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21.apk"
          - "build/fixture-r21/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/full_tests"
          - "--exclude=features/full_tests/[^a-k].*.feature"
          - "--app=build/fixture-r21.apk"
          - "--farm=bb"
          - "--device=ANDROID_10"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: Android 10 NDK r21 end-to-end tests - batch 2'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21.apk"
          - "build/fixture-r21/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/full_tests"
          - "--exclude=features/full_tests/[^l-z].*.feature"
          - "--app=build/fixture-r21.apk"
          - "--farm=bb"
          - "--device=ANDROID_10"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  # Android 11+ devices have the GWP-ASAN tool enabled which randomly samples native memory
  # to detect misuse (such as use-after-free, buffer overflow). If a failure is detected then
  # the device will raise a SIGABRT mentioning GWP-ASAN - this can be investigated further
  # by inspecting the devices logs.
  - label: ':bitbar: Android 11 NDK r21 end-to-end tests - batch 1'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21.apk"
          - "build/fixture-r21/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/full_tests"
          - "--exclude=features/full_tests/[^a-k].*.feature"
          - "--app=build/fixture-r21.apk"
          - "--farm=bb"
          - "--device=ANDROID_11"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: Android 11 NDK r21 end-to-end tests - batch 2'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21.apk"
          - "build/fixture-r21/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/full_tests"
          - "--exclude=features/full_tests/[^l-z].*.feature"
          - "--app=build/fixture-r21.apk"
          - "--farm=bb"
          - "--device=ANDROID_11"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: Android 13 NDK r21 end-to-end tests - batch 1'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21.apk"
          - "build/fixture-r21/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/full_tests"
          - "--exclude=features/full_tests/[^a-k].*.feature"
          - "--app=build/fixture-r21.apk"
          - "--farm=bb"
          - "--device=ANDROID_13"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: Android 13 NDK r21 end-to-end tests - batch 2'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21.apk"
          - "build/fixture-r21/*"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner
        run: maze-runner
        service-ports: true
        command:
          - "features/full_tests"
          - "--exclude=features/full_tests/[^l-z].*.feature"
          - "--app=build/fixture-r21.apk"
          - "--farm=bb"
          - "--device=ANDROID_13"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  # If there is a tag present activate a manual publishing step

  - block: 'Trigger package publish'
    if: build.branch == "master"
    key: trigger-publish
    blocked_state: passed

  - label: ':docker: Build Android base image'
    if: build.branch == "master"
    key: 'android-common'
    timeout_in_minutes: 30
    depends_on: 'trigger-publish'
    plugins:
      - docker-compose#v4.7.0:
          build:
            - android-common
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-common:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:latest
      - docker-compose#v4.7.0:
          push:
            - android-common:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:latest

  - label: 'Publish :rocket:'
    if: build.branch == "master"
    depends_on: 'android-common'
    env:
      BUILDKITE_PLUGIN_S3_SECRETS_BUCKET_PREFIX: bugsnag-android-publish
    plugins:
      docker-compose#v4.7.0:
        no-cache: true
        run: android-publisher
