steps:

  - label: 'Audit current licenses'
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    command: ./scripts/audit-dependency-licenses.sh

  - label: ':android: Build fixture APK r16'
    key: "fixture-r16"
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    artifact_paths:
      - "build/fixture-r16.apk"
      - "build/fixture_r16_url.txt"
      - "build/fixture-r16/*"
    commands:
      - bundle install
      - make fixture-r16
      - bundle exec upload-app --app=./build/fixture-r16.apk --app-id-file=build/fixture_r16_url.txt

  - label: ':android: Build fixture APK r19'
    key: "fixture-r19"
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    artifact_paths:
      - "build/fixture-r19.apk"
      - "build/fixture_r19_url.txt"
      - "build/fixture-r19/*"
    commands:
      - bundle install
      - make fixture-r19
      - bundle exec upload-app --app=./build/fixture-r19.apk --app-id-file=build/fixture_r19_url.txt

  - label: ':android: Build fixture APK r21'
    key: "fixture-r21"
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    artifact_paths:
      - "build/fixture-r21.apk"
      - "build/fixture_r21_url.txt"
      - "build/fixture-r21/*"
    commands:
      - bundle install
      - make fixture-r21
      - bundle exec upload-app --app=./build/fixture-r21.apk --app-id-file=build/fixture_r21_url.txt

  - label: ':android: Coding standards checks'
    timeout_in_minutes: 20
    agents:
      queue: macos-12-arm
    command: './gradlew --continue checkstyle detekt lint ktlintCheck'

  - label: ':android: CppCheck'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    command: 'bash ./scripts/run-cpp-check.sh'

  - label: ':android: ClangFormat'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    command: 'bash ./scripts/run-clang-format-ci-check.sh'

  - label: ':android: Lint mazerunner scenarios'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    commands:
      - cd features/fixtures/mazerunner
      - ./gradlew ktlintCheck detekt checkstyle

  - label: ':android: Android size reporting'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    command: scripts/run-sizer.sh

  - label: ':android: JVM tests'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    command: './gradlew test'

  #
  # BitBar steps
  #

  - label: ':bitbar: Android 9 NDK r21 smoke tests'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21.apk"
          - "build/fixture-r21/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner-bitbar
        run: android-maze-runner-bitbar
        service-ports: true
        command:
          - "features/smoke_tests"
          - "--app=build/fixture-r21.apk"
          - "--farm=bb"
          - "--device=ANDROID_9"
          - "--no-tunnel"
          - "--aws-public-ip"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: Android 10 NDK r21 smoke tests'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21.apk"
          - "build/fixture-r21/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner-bitbar
        run: android-maze-runner-bitbar
        service-ports: true
        command:
          - "features/smoke_tests"
          - "--app=build/fixture-r21.apk"
          - "--farm=bb"
          - "--device=ANDROID_10"
          - "--no-tunnel"
          - "--aws-public-ip"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: Android 11 NDK r21 smoke tests'
    key: 'android-11-smoke'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21.apk"
          - "build/fixture-r21/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner-bitbar
        run: android-maze-runner-bitbar
        service-ports: true
        command:
          - "features/smoke_tests"
          - "--app=build/fixture-r21.apk"
          - "--farm=bb"
          - "--device=ANDROID_11"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

 # Android 11+ devices have the GWP-ASAN tool enabled which randomly samples native memory
  # to detect misuse (such as use-after-free, buffer overflow). If a failure is detected then
  # the device will raise a SIGABRT mentioning GWP-ASAN - this can be investigated further
  # by inspecting the devices logs.
  - label: ':bitbar: Android 12 NDK r21 end-to-end tests - batch 1'
    depends_on:
      - "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21.apk"
          - "build/fixture-r21/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner-bitbar
        run: android-maze-runner-bitbar
        service-ports: true
        command:
          - "features/full_tests"
          - "--exclude=features/full_tests/[^a-k].*.feature"
          - "--app=build/fixture-r21.apk"
          - "--farm=bb"
          - "--device=ANDROID_12"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: Android 12 NDK r21 end-to-end tests - batch 2'
    depends_on:
      - "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21.apk"
          - "build/fixture-r21/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner-bitbar
        run: android-maze-runner-bitbar
        service-ports: true
        command:
          - "features/full_tests"
          - "--exclude=features/full_tests/[^l-z].*.feature"
          - "--app=build/fixture-r21.apk"
          - "--farm=bb"
          - "--device=ANDROID_12"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: Android 13 NDK r21 smoke tests'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21.apk"
          - "build/fixture-r21/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner-bitbar
        run: android-maze-runner-bitbar
        service-ports: true
        command:
          - "features/smoke_tests"
          - "--app=build/fixture-r21.apk"
          - "--farm=bb"
          - "--device=ANDROID_13"
          - "--no-tunnel"
          - "--aws-public-ip"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  #
  # BrowserStack steps
  #
  - label: ':browserstack: Android 7 NDK r19 smoke tests'
    key: 'android-7-smoke'
    depends_on: "fixture-r19"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture_r19_url.txt"
          - "build/fixture-r19/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=@/app/build/fixture_r19_url.txt"
          - "--farm=bs"
          - "--device=ANDROID_7_1"
          - "--appium-version=1.20.2"
          - "--fail-fast"
    concurrency: 24
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r19"

  - label: ':browserstack: Android 8.1 NDK r19 smoke tests'
    key: 'android-8-1-smoke'
    depends_on: "fixture-r19"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture_r19_url.txt"
          - "build/fixture-r19/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=@/app/build/fixture_r19_url.txt"
          - "--farm=bs"
          - "--device=ANDROID_8_1"
          - "--appium-version=1.20.2"
          - "--fail-fast"
    concurrency: 24
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r19"

  - label: 'Conditionally include device farms/full tests'
    agents:
      queue: macos-12-arm
    command: sh -c .buildkite/pipeline_trigger.sh
