FROM openjdk:8-jdk-stretch

RUN apt-get update
RUN apt-get install -y gradle jq

WORKDIR /sdk
RUN wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -q
RUN unzip  -q sdk-tools-linux-4333796.zip

ENV PATH="${PATH}:/sdk/tools:/sdk/tools/bin"

RUN yes | sdkmanager "platform-tools"

ENV PATH="${PATH}:/sdk/platform-tools"
ENV ANDROID_HOME="/sdk/"

WORKDIR /app

COPY gradlew build.gradle settings.gradle gradle.properties /app/
COPY gradle/ /app/gradle/
COPY bugsnag-android/ bugsnag-android/
COPY bugsnag-android-anr/ bugsnag-android-anr/
COPY bugsnag-android-core/ bugsnag-android-core/
COPY bugsnag-android-ndk/ bugsnag-android-ndk/
COPY examples/ examples/
COPY scripts/ scripts/

RUN scripts/install-ndk.sh

RUN ./gradlew

# Everything above this point should be derived from android-base
RUN sed --in-place="" --expression='s/"armeabi",//' bugsnag-android-anr/build.gradle bugsnag-android-ndk/build.gradle
CMD ./scripts/build-instrumentation-tests.sh && ./scripts/run-instrumentation-test.sh
