#FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-v3-cli as android-maze-runner
FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:tms-os-version-cli as android-maze-runner

COPY features features
