# CI test image for unit/lint/type tests
FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:add-android-8.1-and-10-cli as android-maze-runner
RUN apk add --no-cache ruby-dev build-base libffi-dev curl-dev curl

COPY tests/features features
