[versions]
activityCompose = "1.8.0"
agp = "8.10.0"
appcompat = "1.6.1"
bugsnag-android="6.17.0"
bugsnag-gradle = "0.4.0"
composeBom = "2024.09.00"
coreKtx = "1.16.0"
google-android-material = "1.11.0"
kotlin = "2.0.21"
lifecycleRuntimeKtx = "2.6.1"
squareup-okhttp3 = "4.12.0"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat"}
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
bugsnag-android="6.17.0"
bugsnag-okhttp = {group = "com.bugsnag", name = "bugsnag-plugin-android-okhttp", version.ref = "bugsnag-android"}
google-android-material = { group = "com.google.android.material", name = "material", version.ref = "google-android-material"}
squareup-okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "squareup-okhttp3"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
bugsnag-gradle = { id = "com.bugsnag.gradle", version.ref = "bugsnag-gradle"}
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }