# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "danger", "~> 9"
gem "git", ">= 1.13.0" # Force update of git gem to avoid CVE-2022-46648