#!/usr/bin/env bash
set -Eeuo pipefail

# setup_zscaler --project <PATH_TO_ANDROID_PROJECT> [--jdk <PATH_TO_JDK>]
#
# What it does (with loud DO-NOT-COMMIT banners):
# 1) gradle.properties: appends a bannered Zscaler block of systemProp.* values
# 2) res/xml/network_security_config.xml: writes a file with a warning header
# 3) AndroidManifest.xml:
#    - Ensures application@android:networkSecurityConfig is set (and normalizes it)
#    - Inserts a warning comment as the first child of <application>
#    - Upserts Bugsnag HTTP endpoints wrapped with warning comments
#
# Notes:
# - No backups are created.
# - macOS and Linux compatible (uses perl for robust XML-ish edits).

die() { echo "❌ $*" >&2; exit 1; }
info() { echo "➡️  $*"; }
ok()   { echo "✅ $*"; }

JDK_INPUT=""
PROJECT_ROOT=""

# ------- Parse args -------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --jdk) JDK_INPUT="${2:-}"; shift 2 ;;
    --project) PROJECT_ROOT="${2:-}"; shift 2 ;;
    *) die "Unknown argument: $1 (expected --project and optional --jdk)" ;;
  esac
done

[[ -n "$PROJECT_ROOT" ]] || die "--project <PATH_TO_ANDROID_PROJECT> is required"
[[ -d "$PROJECT_ROOT" ]] || die "Android project path not found: $PROJECT_ROOT"

# ------- Resolve JDK / truststore -------
if [[ -z "$JDK_INPUT" ]]; then
  [[ -n "${JAVA_HOME:-}" ]] || die "--jdk not provided and JAVA_HOME is unset"
  info "--jdk not provided; using JAVA_HOME=$JAVA_HOME"
  JDK_INPUT="$JAVA_HOME"
fi
[[ -d "$JDK_INPUT" ]] || die "JDK path not found: $JDK_INPUT"

CANDIDATES=(
  "$JDK_INPUT/lib/security/cacerts"
  "$JDK_INPUT/Contents/Home/lib/security/cacerts"
)
TRUSTSTORE=""
for c in "${CANDIDATES[@]}"; do
  [[ -f "$c" ]] && { TRUSTSTORE="$c"; break; }
done
[[ -n "$TRUSTSTORE" ]] || die "Could not find cacerts under '$JDK_INPUT'. Tried: ${CANDIDATES[*]}"

# ------- Locate project files -------
GRADLE_PROPS="$PROJECT_ROOT/gradle.properties"
[[ -f "$GRADLE_PROPS" ]] || { info "Creating missing gradle.properties at project root"; : > "$GRADLE_PROPS"; }

MANIFEST_PATH="$(find "$PROJECT_ROOT" -type f -path '*/src/main/AndroidManifest.xml' | head -n 1 || true)"
[[ -n "$MANIFEST_PATH" ]] || die "Could not find any */src/main/AndroidManifest.xml in $PROJECT_ROOT"

# …/src/main/AndroidManifest.xml -> module dir is two levels up
MODULE_DIR="$(cd "$(dirname "$MANIFEST_PATH")/../.." && pwd)"
RES_XML_DIR="$MODULE_DIR/src/main/res/xml"
NETWORK_XML="$RES_XML_DIR/network_security_config.xml"

info "Using Android module: $MODULE_DIR"
info "Manifest: $MANIFEST_PATH"

# ======= 1) gradle.properties (bannered block) =======
info "Updating gradle.properties…"

Z_START="### >>> ZSCALER SETUP - DO NOT COMMIT THIS CODE >>>"
Z_END="### <<< END ZSCALER SETUP <<<"
Z_BLOCK=$(cat <<EOF
$Z_START
# These properties were auto-added by scripts/setup_zscaler.sh for corporate proxy/Zscaler
systemProp.javax.net.ssl.trustStore=$TRUSTSTORE
systemProp.javax.net.ssl.trustStorePassword=changeit
systemProp.com.sun.net.ssl.checkRevocation=false
systemProp.sun.security.ssl.allowUnsafeRenegotiation=true
systemProp.sun.security.ssl.allowLegacyHelloMessages=true
$Z_END
EOF
)

# Remove existing bannered block (idempotent), then append fresh one
if grep -qF "$Z_START" "$GRADLE_PROPS"; then
  TMP_GP="$(mktemp)"
  awk -v start="$Z_START" -v end="$Z_END" '
    BEGIN{skip=0}
    index($0,start){skip=1; next}
    index($0,end)  {skip=0; next}
    !skip{print}
  ' "$GRADLE_PROPS" > "$TMP_GP"
  mv "$TMP_GP" "$GRADLE_PROPS"
fi
printf "\n%s\n" "$Z_BLOCK" >> "$GRADLE_PROPS"
ok "gradle.properties updated."

# ======= 2) network_security_config.xml (with header warning) =======
info "Ensuring res/xml/network_security_config.xml…"
mkdir -p "$RES_XML_DIR"
cat > "$NETWORK_XML" <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<!-- ============================================================= -->
<!-- ZSCALER SETUP - DO NOT COMMIT THIS CODE                       -->
<!-- This file was auto-generated by scripts/setup_zscaler.sh      -->
<!-- ============================================================= -->
<network-security-config>
    <!-- Allow cleartext traffic for localhost, emulator, and webhook.site -->
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">10.0.2.2</domain>
        <domain includeSubdomains="true">localhost</domain>
        <domain includeSubdomains="true">127.0.0.1</domain>
        <domain includeSubdomains="true">bugsnag.com</domain>
    </domain-config>

    <!-- Base configuration -->
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <certificates src="system"/>
            <certificates src="user"/>
        </trust-anchors>
    </base-config>

    <!-- Debug overrides - accept all certificates including self-signed -->
    <debug-overrides>
        <trust-anchors>
            <certificates src="system"/>
            <certificates src="user"/>
            <!-- This allows self-signed certificates in debug builds -->
        </trust-anchors>
    </debug-overrides>
</network-security-config>
XML
ok "Created: $NETWORK_XML"

# ======= 3) AndroidManifest.xml (attribute + warnings + endpoints) =======
info "Patching AndroidManifest.xml…"

# 3a) Ensure & normalize application@android:networkSecurityConfig
if ! grep -q 'android:networkSecurityConfig=' "$MANIFEST_PATH"; then
  perl -0777 -i -pe 's/<application\b(?![^>]*android:networkSecurityConfig=)/<application android:networkSecurityConfig="@xml\/network_security_config"/s' "$MANIFEST_PATH"
fi
# Normalize any wrong values (e.g., "/network_security_config")
perl -0777 -i -pe 's/android:networkSecurityConfig="[^"]*"/android:networkSecurityConfig="@xml\/network_security_config"/' "$MANIFEST_PATH"

# 3b) Insert a warning comment as the first child of <application> (once)
if ! grep -q 'ZSCALER SETUP - DO NOT COMMIT THIS CODE' "$MANIFEST_PATH"; then
  perl -0777 -i -pe 's|(<application\b[^>]*>)|\1\n        <!-- ZSCALER SETUP - DO NOT COMMIT THIS CODE: networkSecurityConfig + Bugsnag endpoints -->|s' "$MANIFEST_PATH"
fi

# 3c) Upsert Bugsnag endpoints wrapped with warning comments before </application>
TMP_MANIFEST="$(mktemp)"
# Remove any existing occurrences we manage (simple/conservative)
sed -E '/<meta-data[[:space:]]+android:name="com\.bugsnag\.android\.ENDPOINT_NOTIFY"/,/\/>/d' "$MANIFEST_PATH" \
  | sed -E '/<meta-data[[:space:]]+android:name="com\.bugsnag\.android\.ENDPOINT_SESSIONS"/,/\/>/d' \
  > "$TMP_MANIFEST"

awk '
  BEGIN {
    print_before = "        <!-- ZSCALER SETUP - DO NOT COMMIT THIS CODE: Bugsnag endpoints -->\n" \
                   "        <meta-data android:name=\"com.bugsnag.android.ENDPOINT_NOTIFY\"\n" \
                   "            android:value=\"http://notify.bugsnag.com\"/>\n" \
                   "        <meta-data android:name=\"com.bugsnag.android.ENDPOINT_SESSIONS\"\n" \
                   "            android:value=\"http://sessions.bugsnag.com\"/>\n" \
                   "        <!-- END ZSCALER SETUP -->\n"
  }
  /<\/application>/ && !inserted { printf("%s", print_before); inserted=1 }
  { print }
' "$TMP_MANIFEST" > "$MANIFEST_PATH"
rm -f "$TMP_MANIFEST"
ok "Manifest patched."

echo
ok "All done."
echo "   Project root : $PROJECT_ROOT"
echo "   Module dir   : $MODULE_DIR"
echo "   Manifest     : $MANIFEST_PATH"
echo "   Network XML  : $NETWORK_XML"
echo "   Truststore   : $TRUSTSTORE"